name: Deploy Documentation
on:
  push:
    branches: ["main"]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backend
        uses: actions/checkout@v4
      - name: Checkout Frontend
        uses: actions/checkout@v4
        with:
          repository: FernandoM-99/Sistema-inventario-frontend
          path: sistema-inventario-frontend
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install Docfx
        run: dotnet tool update -g docfx
      - name: Build Docfx
        run: docfx docfx_project/docfx.json
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docfx_project/_site' # Aquí le decimos dónde está el sitio real
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
